### ISSUE TITLE
Reason for seeing "request socket closed" warnings?

### ISSUE THREAD

**Issue by AndrewLane** [tellnes/bunyan-middleware#21] opened 2018-05-23 01:54 UTC
Hello, we are seeing "request socket closed" warnings coming from 

https://github.com/tellnes/bunyan-middleware/blob/cea8b3107134c07dfcc473d24512f284bb9d7141/index.js#L128

However, I am ignorant as to what I'm doing wrong to create that scenario.  Anything simple or obvious?

**Comment by msmol** [comment] 2018-05-31 14:42
I am seeing these warnings as well

Node: 10.2.1
express: 4.16.3
bunyan-middleware: 0.8.0

**Comment by msmol** [comment] 2018-05-31 17:27
Downgrading to Node 8.9.4 seems to disappear the warning. I will continue to investigate

**Comment by msmol** [comment] 2018-05-31 19:46
https://github.com/nodejs/node/issues/21063

Is the root cause

**Comment by ksmithut** [comment] 2018-06-13 22:03
So if that's the correct behavior for the 'close' event to be emitted always, perhaps this log shouldn't be a `warn`? or is it also indicative of `warn` behavior?

**Comment by msmol** [comment] 2018-06-14 14:41
@ksmithut In my opinion it should no longer be logged at all, as a `warn` or otherwise, since it is now a "normal" event that isn't indicative of any problem or out-of-the-ordinary situation. See: https://github.com/tellnes/bunyan-middleware/pull/22/files

**Comment by ksmithut** [comment] 2018-06-14 15:07
@msmol I would agree, I should have looked at the existing PRs 👍

**Comment by msmol** [comment] 2018-06-14 17:08
I opened that PR 2 weeks ago now, and no sign of any activity from the project owner :thinking:

**Comment by tellnes** [comment] 2019-07-29 11:43
Merged the pull request, so closing this.

**Closed by tellnes** 2019-07-29 11:43 UTC
